### ISSUE TITLE
Issues running headless servers

### ISSUE THREAD

**Issue by CosmicHorrorDev** [katubug/CottageWitch119#62]
**What Cottage Witch version are you using?**
Version: 1.15.16

**How much RAM you have allocated (recommended 6-8gb)**
You can check this by viewing your launcher's settings. If you do not have 6gb allocated, please try this first.

6G

**Clearly describe the issue**
Describe what is happening and what you are doing when and after it happens. For example, if your game goes "Not Responding" while loading (which is normal btw), are you clicking on the window? Are you letting it load? Do you have a lot of background processes? etc.

(Obligatory thanks for the modpack!)

I'm trying to run the server on a headless linux setup through docker and I'm running into issues with the server seemingly expecting an X11 display server to be running which isn't a thing on my headless setup. When initially setting up there was a failure that seemed to be caused by missing `libXtst.so.6`. Installing `libxtst6` was an easy enough fix for that error, but now it starts failing on trying to bind to an X11 session which is obviously going to be an issue on a headless server

_Snippet from the logs (specifically the "Can't connect to X11 window server ...)_

```text
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:224)
        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599)
        at java.desktop/javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:668)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.gui.MinecraftServerGui.m_139921_(MinecraftServerGui.java:47)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_139667_(DedicatedServer.java:350)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.lambda$main$5(Main.java:214)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129872_(MinecraftServer.java:253)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:198)
        ... 13 more
```

**Screenshots**
Attach relevant screenshots here.

**Comment by katubug** [comment]
Hi! I wish I could say I was equipped to handle this, but honestly I'm not at all familiar with Linux and I'm also not great with self hosting.

I am assuming you're running it from the serverstart.sh and not .bat? Those files are adapted from the ATM server start files, I didn't author them, so I'm not fully aware of what they contain - I'm on my phone so I can't check. But the bat may contain references to Windows. Do batch files even work on Linux? Lol.

If you've completed the initial server installation, I'd try launching the server through a different script which is made for your environment - I don't know what that entails but I'm certain there's one online.

If it turns out it's a problem with the installation instead of the launch script, I'd do the installation on a local Windows machine (if you have one) and then upload the modpack to your server manually.

If these steps don't help, I recommend asking at the modded mc discord: https://discord.gg/moddedmc

They're very knowledgeable in the server admin channel. I'm happy to help in any way I can if you need to ask follow up questions, I'm just not personally very strong on this topic.

Thank you for the kind words!

**Comment by CosmicHorrorDev** [comment]
I managed to get a workaround working. To give the full context I'm running things through `docker` using the docker images from [`itzg/docker-minecraft-server`](https://github.com/itzg/docker-minecraft-server)

In case anyone finds themselves in a similar situation the flow to get things started is to try creating a new server deployment

```bash
$ docker run -it --name cottage_witch \
    -p 25565:25565 \
    -v /host/dir/server:/data \
    -e EULA=TRUE \
    -e MEMORY=6G \
    -e TYPE=AUTO_CURSEFORGE \
    -e CF_PAGE_URL='https://www.curseforge.com/minecraft/modpacks/cottage-witch' \
    -e CF_API_KEY='REDACTED' \
    itzg/minecraft-server:java17-jdk
```

That will fail with mods that need to be manually downloaded since authors can choose to disable automatic downloads if you're not curseforge :cry:. Manually download all of the mods listed in `/host/dir/server/MODS_NEED_DOWNLOAD.txt` into `/host/dir/server/mods`

**IMPORTANT:** To get the server to launch without trying to interact with the GUI you need to add `nogui` to the bottom of `/host/dir/server/libraries/net/minecraftforge/forge/1.19.2-43.3.5/unix_args.txt`

**ALSO IMPORTANT:** The server will fail to launch if you don't have `libXtst.so.6` which is common in minimal environments like `docker` servers. The error looks like this

```text
[01:37:27] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: /opt/java/openjdk/lib/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@19272b27 handleEvent(Lnet/minecraftforge/registries/RegisterEvent;)V
                2: ASM: net.minecraftforge.registries.DeferredRegister$EventDispatcher@4b20b960 handleEvent(Lnet/minecraftforge/registries/RegisterEvent;)V
...
```

This can be installed in the container while it's running (so either if you're fast enough to install before the initial `docker run` fails or with a `docker start cottage_witch`)

```bash
$ docker exec cottage_witch /bin/bash -c "sudo apt install -y libxtst6"
```

After all that the server should launch normally if you go to start it

```bash
$ docker restart cottage_witch
```

---

I'm fine with this workaround in terms of fixing this issue, but it's the first time I've had a modded minecraft server where this has happened

**Comment by banorawhite** [comment]
Ran into this issue as well as I was using a managed server that's pulling a Docker image. Error disappeared after I removed [Client Side Mods](../wiki/Client-Side-Mods). Did not bother to identify which mod/s causes this.
