### ISSUE TITLE
[Crash] Game gives an error message and crashes shortly after

### ISSUE THREAD

**Issue by Melancholy-AVI** [katubug/CottageWitch119#73]
**What Cottage Witch version are you using?**
Version: 1.16.5hotfix

**What were you doing when you crashed?**
I opened the game from the curseforge launcher and get this error message

**Screenshots**
![image](https://github.com/katubug/CottageWitch119/assets/169413107/8261ca07-f6f5-45d2-8065-a5f5a9fe9c52)

**Crash Reports or Latest.log**
[20:37:16] [INIT] KubeJS 1902.6.2-build.69; MC 1902 forge
[20:37:16] [INIT] Loaded plugins:
[20:37:16] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgePlugin
[20:37:16] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgeClientPlugin
[20:37:16] [INIT] - com.bobvarioa.kubejsarsnouveau.KubeJSArsNouveauPlugin
[20:37:16] [INIT] - dev.latvian.mods.kubejs.create.KubeJSCreatePlugin
[20:37:16] [INIT] - com.almostreliable.morejs.Plugin
[20:37:17] [INFO] Loaded script startup_scripts:brewing.js in 0.101 s
[20:37:17] [INFO] Loaded script startup_scripts:items.js in 0.002 s
[20:37:17] [INFO] script.js#3: Hello, World! (You will only see this line once in console, during startup)
[20:37:17] [INFO] Loaded script startup_scripts:script.js in 0.001 s
[20:37:17] [INFO] startup.js#3: Hello, World! (You will only see this line once in console, during startup)
[20:37:17] [INFO] Loaded script startup_scripts:startup.js in 0.002 s
[20:37:17] [INFO] Loaded 4/4 KubeJS startup scripts in 0.944 s
[20:37:36] [ERROR] ! Error occurred while handling event 'MoreJSEvents.registerPotionBrewing': java.lang.IllegalArgumentException: Top input must have at least one item
[20:37:36] [ERROR] ! java.lang.IllegalArgumentException: Top input must have at least one item
[20:37:36] [ERROR] ! 	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[20:37:36] [ERROR] ! 	at TRANSFORMER/morejs@0.3.0/com.almostreliable.morejs.features.potion.PotionBrewingRegisterEvent.validate(PotionBrewingRegisterEvent.java:24)
[20:37:36] [ERROR] ! 	at TRANSFORMER/morejs@0.3.0/com.almostreliable.morejs.features.potion.PotionBrewingRegisterEventForge.addCustomBrewing(PotionBrewingRegisterEventForge.java:25)
[20:37:36] [ERROR] ! 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:37:36] [ERROR] ! 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[20:37:36] [ERROR] ! 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:37:36] [ERROR] ! 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:987)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:370)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.doTopCall(Context.java:1325)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[20:37:36] [ERROR] ! 	at TRANSFORMER/rhino@1902.2.3-build.284/dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[20:37:36] [ERROR] ! 	at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy101.onEvent(Unknown Source)
[20:37:36] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.69/dev.latvian.mods.kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[20:37:36] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.69/dev.latvian.mods.kubejs.event.EventHandler.postToHandlers(EventHandler.java:301)
[20:37:36] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.69/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:271)
[20:37:36] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.69/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:225)
[20:37:36] [ERROR] ! 	at TRANSFORMER/kubejs@1902.6.2-build.69/dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:178)
[20:37:36] [ERROR] ! 	at TRANSFORMER/morejs@0.3.0/com.almostreliable.morejs.MoreJSForge.onClientCommon(MoreJSForge.java:31)
[20:37:36] [ERROR] ! 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
[20:37:36] [ERROR] ! 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
[20:37:36] [ERROR] ! 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[20:37:36] [ERROR] ! 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[20:37:36] [ERROR] ! 	at LAYER PLUGIN/javafmllanguage@1.19.2-43.3.5/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114)
[20:37:36] [ERROR] ! 	at LAYER PLUGIN/fmlcore@1.19.2-43.3.5/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122)
[20:37:36] [ERROR] ! 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[20:37:36] [ERROR] ! 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[20:37:36] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[20:37:36] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[20:37:36] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[20:37:36] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[20:37:36] [ERROR] ! 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
**Additional context**

**Comment by katubug** [comment]
Hi, thank you for reporting! Is this your first install or did you update a previous installation of the modpack? Did you create a new profile for it?

**Comment by Melancholy-AVI** [comment]
this is my first install

**Comment by katubug** [comment]
Gotcha! Have you added, removed, or updated any mods?

**Comment by Melancholy-AVI** [comment]
I havent, no. should i try uninstalling and reinstalling? i have no idea why i havent tried

**Comment by katubug** [comment]
Yes, try reinstalling. If that doesn't work, try deleting `/kubejs/startup_scripts/brewing.js`
