### ISSUE TITLE
Error-Code -805306369   [Crash]

### ISSUE THREAD

**Issue by Sunnyrose000** [katubug/CottageWitch119#87]
**What Cottage Witch version are you using?**
Version: 1.19.2

**What were you doing when you crashed?**
A clear and concise description of what happened.

I tried to log in my World,but then it just stops loading and i cant do anything,exept for closing Minecraft and then the error code -805306369 pops up

**To Reproduce**

**Screenshots**

**Crash Reports or Latest.log**
21:48:52.567
Puzzles Lib
Server thread
Loading server config for easyanvils
21:48:52.615
net.minecraft.server.MinecraftServer
Server thread
Encountered an unexpected exception
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file ars_nouveau/glyph_projectile.toml of type SERVER for modid ars_nouveau
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.5/net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47)
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.5/net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60)
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.5/net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.5/net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50)
	at TRANSFORMER/forge@43.3.5/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:90)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:61)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
	at LAYER PLUGIN/fmlcore@1.19.2-43.3.5/net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:43)
	... 10 more
21:48:52.671
net.minecraftforge.common.ForgeMod
Server thread
Preparing crash report with UUID da4df279-2421-4d01-a062-32aef352ea59
21:48:52.671
net.minecraft.server.MinecraftServer
Server thread
This crash report has been saved to: C:\Users\PC\curseforge\minecraft\Instances\Cottage Witch (2)\crash-reports\crash-2024-07-31_21.48.52-server.txt
21:48:52.672
net.minecraft.server.MinecraftServer
Server thread
Stopping server
21:48:52.672
net.minecraft.server.MinecraftServer
Server thread
Saving players
21:48:52.672
net.minecraft.server.MinecraftServer
Server thread
Saving worlds
21:48:52.672
net.minecraft.server.MinecraftServer
Server thread
Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.m_6857_()" because "serverlevel2" is null
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:502)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:575)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_7041_(IntegratedServer.java:173)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:682)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)
21:48:52.883
configured
Server thread
Unloading server configs...
/

**Additional context**

**Comment by katubug** [comment]
Hi, please follow the directions in the template. Without your log or crash report, I can't help

**Comment by Sunnyrose000** [comment]
i hope it's fine now

**Comment by Sunnyrose000** [comment]
Help plsss :(

**Comment by katubug** [comment]
Hi, sorry but that's not the crash report. Can you look in your/crash-reports/ folder and upload the latest one?

**Comment by katubug** [comment]
No worries at all, I'm glad you got it sorted!
